### ISSUE TITLE
能否添加一个正版用的登录的判断逻辑，就像Authlib-Agent里面的一样。

### ISSUE THREAD

**Issue by ChenhaoShen** [bs-community/yggdrasil-api#2]
能否添加一个正版用的登录的判断逻辑，当正版用户登录的时候转发登录请求到Mojang的服务器来验证。

**Comment by prinsss** [comment]
有打算做，但是可能短时间内不会实现（就我所知，此功能的用户需求不大）。

**Comment by yushijinhun** [comment]
authlib-agent 对这个问题的解决方法是失败的，见： to2mbn/authlib-agent#13 , to2mbn/authlib-agent#20

**Comment by prinsss** [comment]
由于本 issue 在过去的两个月中没有任何回应，我们决定将其关闭。
