### ISSUE TITLE
Airme将在3.0.0.0Beta2版本支持对皮肤站的操作支持

### ISSUE THREAD

**Issue by SagiriYuuki** [bs-community/yggdrasil-api#20]
当前还在测试阶段，现在是Beta1
大约一周左右时间推送Beta2

奥利给干就完了！

**Comment by tnqzh123** [comment]
只是吐槽一下…

这也要发个 Issue…？

**Comment by SagiriYuuki** [comment]
在MCBBS私聊的时候不是让我提一个Issus嘛....


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Steven Qiu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 晚上10:04
收件人:&nbsp;"bs-community/yggdrasil-api"<yggdrasil-api@noreply.github.com&gt;;
抄送:&nbsp;"夏了个沫"<1037440126@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bs-community/yggdrasil-api] Airme将在3.0.0.0Beta2版本支持对皮肤站的操作支持 (#20)




只是吐槽一下…
 
这也要发个 Issue…？

**Comment by g-plane** [comment]
考虑到启动器不开源（之前没发现），暂时不考虑接受。

**Comment by SagiriYuuki** [comment]
感谢回复。上一代其实开源了的，airme3暂时不考虑开源，因为开源了的话会导致一大批易语言启动器泛滥。------------------ 原始邮件 ------------------
发件人: "Pig Fang"<notifications@github.com>
发送时间: 2020年1月5日(星期天) 中午1:35
收件人: "bs-community/yggdrasil-api"<yggdrasil-api@noreply.github.com>;
抄送: "夏了个沫"<1037440126@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [bs-community/yggdrasil-api] Airme将在3.0.0.0Beta2版本支持对皮肤站的操作支持 (#20)



考虑到启动器不开源（之前没发现），暂时不考虑接受。
 
&mdash;

**Comment by tnqzh123** [comment]
（无关话题）Airme 是易语言写的吗？

**Comment by SagiriYuuki** [comment]
是的------------------ 原始邮件 ------------------
发件人: "Steven Qiu"<notifications@github.com>
发送时间: 2020年1月5日(星期天) 中午1:50
收件人: "bs-community/yggdrasil-api"<yggdrasil-api@noreply.github.com>;
抄送: "夏了个沫"<1037440126@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [bs-community/yggdrasil-api] Airme将在3.0.0.0Beta2版本支持对皮肤站的操作支持 (#20)



（无关话题）Airme 是易语言写的吗？
 
&mdash;
