### ISSUE TITLE
建议增加 自定义API的某些链接与字段 的功能

### ISSUE THREAD

**Issue by SerinaNya** [bs-community/yggdrasil-api#21]
在目前的api中，“启动器配置教程”的链接，总会指向[GitHub](https://github.com/bs-community/yggdrasil-api/wiki/0x03-%E9%85%8D%E5%90%88-authlib-injector-%E4%BD%BF%E7%94%A8#%EF%B8%8F-%E9%85%8D%E7%BD%AE%E5%90%AF%E5%8A%A8%E5%99%A8)。而众所周知，githubusercontent被污染了，图片无法查看。另一方面，一部分皮肤站拥有自己的[用户指引站点](https://littleskin.cn/manual/advanced-usage/yggdrasil.html#%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8)，站点上的内容完全可以与原文媲美。
因此，建议增加一个**自定字段与链接**的功能。方便皮肤站的日常管理运维。

![image](https://user-images.githubusercontent.com/34389622/72338545-acb00a80-36ff-11ea-858f-830aa052c68c.png)

**Comment by g-plane** [comment]
我个人认为，没太大必要。
