### ISSUE TITLE
服务端启用java代理authlib-injector报错

### ISSUE THREAD

**Issue by HoshinoSuzumi** [bs-community/yggdrasil-api#22]
`[authlib-injector.config] [SEVERE] Failed to fetch metadata: java.io.IOException: Server returned HTTP response code: 403 for URL: https://mcskin.boxmoe.cn/api/yggdrasil/`

**Comment by HoshinoSuzumi** [comment]
直接访问yggdrasil api是可以访问到的
[https://mcskin.boxmoe.cn/api/yggdrasil/](https://mcskin.boxmoe.cn/api/yggdrasil/)

**Comment by Asnxthaony** [comment]
看起来你正在使用 `Cloudflare`
在 DNS 选项卡中，单击黄色的云朵，将 `Proxied` 改为 `DNS only` 即可

**Comment by Asnxthaony** [comment]
若您不希望源站 IP 泄漏。
在 `Firewall` 应用中的 `Settings` 选项卡中，关闭 `Browser Integrity Check` 即可。

![image](https://user-images.githubusercontent.com/12845643/73099064-a69f0280-3f25-11ea-8257-c209411f72e6.png)

**Comment by HoshinoSuzumi** [comment]
好的，问题已经解决，非常感谢
![image](https://user-images.githubusercontent.com/26276464/73040933-66dd0a00-3e96-11ea-94de-ae9cbd0661b0.png)
