### ISSUE TITLE
[bug report] 角色更名时UUID会重新生成

### ISSUE THREAD

**Issue by k3-cat** [bs-community/yggdrasil-api#24]
UUID应该全局唯一而且在角色的生命周期内固定
但是yggdrasil-api目前的实现  在更改角色名的时候  UUID也会重新生成
这种设计会导致玩家在改名后无法继承原先的数据 (新的插件都以玩家UUID为依据记录数据

**Comment by Asnxthaony** [comment]
See https://github.com/bs-community/yggdrasil-api/blob/master/bootstrap.php#L49

**Comment by k3-cat** [comment]
啊 不好意思
