### ISSUE TITLE
v3生成的UUID与服务器不一致

### ISSUE THREAD

**Issue by MlgmXyysd** [bs-community/yggdrasil-api#25]
把[算法](https://gist.github.com/games647/2b6a00a8fc21fd3b88375f03c9e2e603)单独拿出来运行生成的UUID和服务器生成的是一样的，在api里的UUID就不一致

如：我的ID为mlgmxyysd，服务器和单独运行算法出来的UUID都是`string(32) "b8cac6baf27c3899a02a5ae498779616"`，皮肤站给的UUID是`string(32) "d5993c8e29d14124bb09ff71a07ecb10"`

**Comment by g-plane** [comment]
原因我也不清楚。我打上「help wanted」的标签了。

**Comment by MlgmXyysd** [comment]
已找到原因，用户经由mojang_verifications插件认证之后的UUID会被替换为正版的uuid，从而导致v3生成机制失效，建议：实时通过v3算法生成
