### ISSUE TITLE
[1.15.2]←请问是否支持

### ISSUE THREAD

**Issue by EnterFor** [bs-community/yggdrasil-api#30]
介绍页没有相关说明，想了解下支持1.15.2的Forge吗？
（可能这么问题有点憨批。。）

**Comment by tnqzh123** [comment]
这个问题应该问 authlib-injector。

和有无 Forge 无关，只要 Mojang 不对 Authlib 做出破坏性变更，一般都能支持。

**Comment by EnterFor** [comment]
谢谢你
