### ISSUE TITLE
仓库合并到 blessing-skin-plugins

### ISSUE THREAD

**Issue by g-plane** [bs-community/yggdrasil-api#32]
出于工程需要，现考虑将本仓库合并到 bs-community/blessing-skin-plugins。详细情况如下：

由于近期在给 Blessing Skin 插件的 JavaScript 代码迁移到 TypeScript；同时计划对 Blessing Skin 插件的文本实现 i18n，并考虑提交到 Crowdin 以便进行统一的翻译管理，需要将代码集中到同一个仓库中。所以，要把这个仓库合并到 bs-community/blessing-skin-plugins 中。

与此同时，我们还考虑将此仓库代码的开源许可证改为 MIT，以保证统一。对于这一点，我们需要得到所有 contributor 的同意： @printempw @yushijinhun @Asnxthaony @outtimes 。

感谢各位的支持。

**Comment by prinsss** [comment]
我没意见👌

**Comment by tnqzh123** [comment]
> 你问我滋磁不滋磁，我说滋磁，我就明确告诉你。

我的意见和上面那句话的意思一样（

**Comment by yushijinhun** [comment]
我无意见

**Comment by hiouttime** [comment]
我无意见

**Comment by g-plane** [comment]
再次谢谢各位。
